### ISSUE TITLE
Make 0.1+ python3 only 

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/ping-python#112]
From @ES-Alexander:

can we mark 0.1.0 as python3 only? Pip installing with no specified version using python2 gets 0.1.0 instead of 0.0.10, which then doesn't work because it includes type hints and various other python3-only things.

**Comment by ES-Alexander** [comment]
Verified working as expected now - thanks! :-)

**Comment by patrickelectric** [comment]
Thanks for finding it!
