### ISSUE TITLE
deal with in_waiting/inWaiting() changes in PySerial

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/ping-python#29]
Brian had [this issue](https://stackoverflow.com/questions/44636075/attributeerror-serial-object-has-no-attribute-in-waiting).
We should either work with both versions or require the newer one, might be good the check how available is the newer version.

**Comment by ES-Alexander** [comment]
`in_waiting` used since #68. Was introduced to pySerial in v3.0 (released 2015) and is available for Python 3.2 and above, so shouldn't be an issue.
