### ISSUE TITLE
Align pypi version with setup.py

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/ping-python#45]
pip search says current is 0.0.3
```
$ pip search bluerobotics-ping | grep bluerobotics-ping
bluerobotics-ping (0.0.3)               - A python module for the Blue Robotics Ping1D echosounder
```

pip install says the latest available is 0.0.2
```
$ pip install bluerobotics-ping==
Collecting bluerobotics-ping==
  Could not find a version that satisfies the requirement bluerobotics-ping== (from versions: 0.0.1.dev4, 0.0.1.dev5, 0.0.1, 0.0.2)
No matching distribution found for bluerobotics-ping==
```

setup.py says 0.0.1: https://github.com/bluerobotics/ping-python/blob/master/setup.py#L9

Let's cut a new release and clean up this situation (we must leave the current versions in pypi for now, as companion depends on 0.0.2).

**Comment by jaxxzer** [comment]
@Williangalvani do you have any clue why there is a difference between pip install and search?

**Comment by Williangalvani** [comment]
It also looks like we never made a release using Travis (tag matching setup.py version). We should do that with this one and make sure it is working ok.
