### ISSUE TITLE
Creating a PingMessage instance always causes KeyError exception

### ISSUE THREAD

**Issue by DimitriosParaschos** [bluerobotics/ping-python#62]
In Ping1D's request() method, which is used by virtually every other communication method (including initialize()), you first create an empty PingMessage instance.
However, this causes PingMessage's constructor (__init__) to assign a message_id of 0, which immediately causes a KeyError in lines 465-480 of pingmessage.py.
As it stands, the Ping1D class is unusable. Please FIX it.
Thank you

James

**Comment by jaxxzer** [comment]
Things are in beta and changing. Right now master is broken. Please try a release: https://github.com/bluerobotics/ping-python/releases

**Comment by DimitriosParaschos** [comment]
Thanks version 0.0.7 worked fine
