### ISSUE TITLE
Ping

### ISSUE THREAD

**Issue by danoloo** [bluerobotics/ping-python#97]

**Comment by patrickelectric** [comment]
Hi @danoloo, do you have any issue to share with us or suggestion ?

**Comment by Williangalvani** [comment]
Pong

**Comment by danoloo** [comment]
> Hi @danoloo, do you have any issue to share with us or suggestion ?

Hello, maybe I will be asking for you assistance along the way as I learn to code.

**Comment by patrickelectric** [comment]
Be free to get in touch in our forum: https://discuss.bluerobotics.com/
